### ISSUE TITLE
Relative Distance Fails on Some Datasets

### ISSUE THREAD

**Issue by GrantDaly** [biocore-ntnu/pyranges#105]
## Stack Trace

Traceback (most recent call last):
  File "/home/grant/anaconda3/lib/python3.7/pdb.py", line 1701, in main
    pdb._runscript(mainpyfile)
  File "/home/grant/anaconda3/lib/python3.7/pdb.py", line 1570, in _runscript
    self.run(statement)
  File "/home/grant/anaconda3/lib/python3.7/bdb.py", line 585, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "/home/grant/pyranges/tests/stats/test_relative_distance.py", line 12, in <module>
    import pytest
  File "/home/grant/pyranges/tests/stats/test_relative_distance.py", line 48, in test2
    print(peaks1.stats.relative_distance(peaks2))
  File "/home/grant/pyranges/pyranges/statistics.py", line 201, in relative_distance
    result = pyrange_apply(_relative_distance, self, other, **kwargs)  # pylint: disable=E1132
  File "/home/grant/pyranges/pyranges/multithreaded.py", line 264, in pyrange_apply
    result = call_f(function, nparams, df, odf, kwargs)
  File "/home/grant/pyranges/pyranges/multithreaded.py", line 22, in call_f
    return f.remote(df, odf, kwargs)
  File "/home/grant/pyranges/pyranges/methods/statistics.py", line 13, in _relative_distance
    left_idx_shift = (midpoints_other[left_idx] > midpoints_self) & (left_idx >
IndexError: index -1 is out of bounds for axis 0 with size 0
Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program
> /home/grant/pyranges/pyranges/methods/statistics.py(13)_relative_distance()
-> left_idx_shift = (midpoints_other[left_idx] > midpoints_self) & (left_idx >
(Pdb) left_idx
array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1])
(Pdb) midpoints_self
array([ 25009500,  40155500,  41232500,  52790500,  53562500,  67700500,
        71546500, 100430500, 101443500, 107917500, 113522500, 119469500,
       153932500])
(Pdb) midpoints_other[left_idx]
*** IndexError: index -1 is out of bounds for axis 0 with size 0
(Pdb) midpoints_other
array([], dtype=int64)
(Pdb) 

## Please let me know if I need to provide more information. Thanks in advance.

**Comment by endrebak** [comment]
Thanks. I’ll try creating a reproducible example and have a look :)

**Comment by endrebak** [comment]
```
import pyranges as pr

import numpy as np

np.random.seed(0)

length1 = np.random.randint(1, int(1e6))
length2 = np.random.randint(1, int(1e6))

print(length1)
print(length2)

gr1, gr2 = pr.random(n=length1), pr.random(n=length2)
print(gr1)
print(gr2)

print(gr1.stats.relative_distance(gr2))
```

```

**Comment by GrantDaly** [comment]
Great, thank you very much. Otherwise the library is very convenient and I plan to use it going forward.

**Comment by endrebak** [comment]
I am very happy to hear that :)

**Comment by endrebak** [comment]
It seems like the only problem was that I had not checked for the case where one pyranges contained more chromosomes or strands than the other. I have pushed a fix to https://github.com/biocore-ntnu/pyranges/pull/111 should be out within a day :)

**Comment by endrebak** [comment]
Thanks again for reporting :)
