### ISSUE TITLE
add/assign column to pyranges df

### ISSUE THREAD

**Issue by wdecoster** [biocore-ntnu/pyranges#126]
I can't figure out how to add a new column to a pyranges (df) object, which should consist of a unique incrementing index and a "Name" field

What I have:
```
chr1  123 456  Foo
chr2  789 1230  Bar
chr3  111 222  Baz
```
What I want:
```
chr1  123 456  Foo 1_Foo
chr2  789 1230  Bar 2_Bar
chr3  111 222  Baz 3_Baz
```

I tried the assign function with the enumerate function or passing an index kwargs, but it seems this gets called separately per chromosome, so my unique incrementing index gets reset all the time.

**Comment by endrebak** [comment]
```
import pyranges as pr
import pandas as pd
import numpy as np

gr = pr.from_string("""Chromosome Start End Name
chr1  123 456  Foo
chr2  789 1230  Bar
chr3  111 222  Baz""")
gr.Name = pd.Series(np.arange(len(gr))).astype(str) + "_" + gr.Name
```

**Comment by endrebak** [comment]
Please use `gr.to_example()` for a copy-pasteable example :)

```
{'Chromosome': ['chr1', 'chr2', 'chr3'],
 'Start': [123, 789, 111],
 'End': [456, 1230, 222],
 'Name': ['0_Foo', '1_Bar', '2_Baz']}
```

Or `from_string` like above :)

**Comment by wdecoster** [comment]
Ahha thanks! Is `gr["Name"]` then not entirely equivalent to `gr.Name`?

**Comment by endrebak** [comment]
No, this should be explained in the docs, I guess.

I use gr[strring] to look up on chromosome or strand.

I guess I could make gr[string] look up columns if there are no chromosomes
or strands with name string in the pyranges...

This overloads the [] getitem-operator, which makes it harder to reason
about. How much of a problem that would be in practice I dunno.

**Comment by wdecoster** [comment]
That's good to know. With pandas I prefer using the df["columnname"] notation over df.columnname notation, to avoid accidentally using a method/attribute (in the current or future version).

**Comment by wdecoster** [comment]
This is probably unrelated, but maybe you can help:

# WORKS
pd.Series(np.arange(len(gr)).astype(str)  + gr.Name.astype(str)) 
# ERRORS
pd.Series(np.arange(len(gr)).astype(str) + '-' + gr.Name.astype(str)) 

Traceback (most recent call last):
  File "/home/wouter/local-repos/misc/mastrdesign.py", line 84, in <module>
    main()
  File "/home/wouter/local-repos/misc/mastrdesign.py", line 10, in main
    variants = get_input(args.VCF)
  File "/home/wouter/local-repos/misc/mastrdesign.py", line 32, in get_input
    gr.Identifier = pd.Series(np.arange(len(gr)).astype(str) + '-' + gr.Name.astype(str))
numpy.core._exceptions.UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U21'), dtype('<U21')) -> dtype('<U21')

**Comment by endrebak** [comment]
Paranthesis error:

`pd.Series(np.arange(len(gr)).astype(str) + '-' + gr.Name.astype(str))`

should be

`pd.Series(np.arange(len(gr))).astype(str) + '-' + gr.Name.astype(str)`

Method chains are much easier to read than nested function calls.

**Comment by wdecoster** [comment]
Oh, heh, thanks! Working at home with a baby apparently doesn't make me any smarter ;)

I'm not sure why, but I also needed `gr.Name.tolist()`. Anyway, solved!

**Comment by endrebak** [comment]
That is okay :) I have special fu for seeing such things as I love lisps. Congrats on the baby :)

Where did you need `.tolist()`? Just curious.

**Comment by wdecoster** [comment]
Without .tolist() on gr.Name I got:

```
['0_EPHA2', '0_ADAM17', '0_SUMF1', '0_NIPAL1', '0_PDCD6', '0_SIRT5', '0_PRPS1L1', '0_C8orf34', '0_MTAP', '0_PFKP', '0_TMEM80', '0_KDM5A', '0_LNX2', '0_NGDN', '0_GOLGA6L2', '0_TBL3', '0_NXN', '0_ENOSF1', '0_GRIN3B', '0_DEFB126', '0_AF165138.7', '0_CDC45', '0_TLR8', '1_PTPRU', '1_NBAS', '1_CAMK1', '1_OCIAD2', '1_SLC6A18', '1_CAP2', '1_FAM221A', '1_CRISPLD1', '1_TAF1L', '1_PITRM1', '1_MUC5AC', '1_VWF', '1_N4BP2L2', '1_KIAA0391', '1_RYR3', '1_MEFV', '1_MYO1C', '1_MYOM1', '1_EVI5L', '1_SPEF1', '1_TXNRD2', '1_CYBB', '2_PTP4A2', '2_ASXL2', '2_FBXL2', '2_SRD5A3', '2_ERBIN', '2_FLOT1', '2_EEPD1', '2_AGO2', '2_KIAA1161', '2_SLC39A12', '2_OR52E8', '2_C1RL', '2_RFXAP', '2_BMP4', '2_VPS18', '2_TEKT5', '2_CAMKK1', '2_MYOM1', '2_MAP2K7', '2_PRNP', '2_COMT', '2_MAGED1', '3_MACF1', '3_GTF3C2', '3_PLCD1', '3_SCARB2', '3_HMGCR', '3_CCHCR1', '3_EEPD1', '3_MROH5', '3_VCP', '3_AGAP14', '3_DNHD1', '3_CD163L1', '3_SMAD9', '3_FBXO34', '3_TYRO3', '3_ZC3H7A', '3_PELP1', '3_ASXL3', '3_DNMT1', '3_RIN2', '3_TOP3B', '3_GNL3L', '4_CFAP57', '4_DHX57', '4_FYCO1', '4_COPS4', '4_ELL2', '4_CMTR1', '4_PGAM2', '4_ZNF696', '4_OR13J1', '4_HERC4', '4_PPFIBP2', '4_CD163L1', '4_VWA8', '4_PRKCH', '4_PLA2G4E', '4_SMG1', '4_VMO1', '4_EPG5', '4_ICAM3', '4_PHF20', '4_IGLV4-60', '4_GPRASP1', '5_KLF17', '5_DOK1', '5_FYCO1', '5_ANK2', '5_SLU7', '5_OARD1', '5_CAMK2B', '5_IARS', '5_DUSP13', '5_LMO2', '5_DDX47', '5_BORA', '5_HSPA2', '5_FBN1', '5_DNAH3', '5_NEURL4', '5_ELL', '5_VSTM2L', '5_HORMAD2', '5_VSIG1', '6_EIF2B3', '6_AC116050.1', '6_DNAH12', '6_PRSS48', '6_F12', '6_NFKBIE', '6_ABCA13', '6_NCBP1', '6_PI4K2A', '6_F2', '6_ATF7IP', '6_SLITRK6', '6_FNTB', '6_CLK3', '6_PALB2', '6_TP53', '6_ZNF568', '6_RPRD1B', '6_APOL4', '6_GRIA3', '7_HECTD3', '7_VWA3B', '7_CNTN3', '7_NPY1R', '7_KLHL31', '7_FIGNL1', '7_NANS', '7_CACUL1', '7_NDUFS3', '7_PLEKHA5', '7_ADPRHL1', '7_ASB2', '7_CYP1A1', '7_XPO6', '7_TOP3A', '7_CAPN12', '7_PLTP', '7_SREBF2', '7_BCAP31', '8_IPP', '8_INPP4A', '8_EPHA6', '8_GABRR1', '8_TPST1', '8_MEGF9', '8_TIAL1', '8_OR1S1', '8_ITPR2', '8_IFI27', '8_UBE2Q2', '8_ADGRG5', '8_PROCA1', '8_EID2', '8_MMP9', '8_CYP2D6', '9_GBP1', '9_UNC50', '9_CLDN16', '9_PREP', '9_POMZP3', '9_SCAI', '9_TIAL1', '9_OR4D10', '9_ITPR2', '9_IQGAP1', '9_SLC9A5', '9_SSH2', '9_LTBP4', '9_ZMYND8', '9_MIOX', '10_PRMT6', '10_TTN', '10_IL1RAP', '10_SLC35F1', '10_CROT', '10_ANGPTL2', '10_ACTN3', '10_DENND5B', '10_IQGAP1', '10_IL34', '10_LASP1', '10_BCL2L12', '10_FAM65C', '11_KIAA1324', '11_COL5A2', '11_SDHAP1', '11_THEMIS', '11_GAL3ST4', '11_NTNG2', '11_ARAP1', '11_ASB8', '11_IGF1R', '11_PHLPP2', '11_KRT9', '11_CTB-147C22.8', '11_CYP24A1', '12_AL450992.2&THEM5', '12_RAPH1', '12_LAMA2', '12_PILRB', '12_ENTPD2', '12_ATG16L2', '12_DDX23', '12_PKD1L2', '12_FAM117A', '12_KLK12', '12_PCK1', '13_LMNA', '13_PIKFYVE', '13_TAAR9', '13_ZNF277', '13_ARRB1', '13_TNS2', '13_NECAB2', '13_VMP1', '13_SIGLEC12', '13_LAMA5', '14_NTRK1', '14_PECR', '14_ADGRG6', '14_AKR1D1', '14_EMSY', '14_PRIM1', '14_ATP2C2', '14_JMJD6', '14_COL20A1', '15_CFAP126', '15_STK16', '15_DACT2', '15_ZC3HAV1', '15_KDM4D', '15_GAS8', '15_RNF213', '16_PRRC2C', '16_BRAF', '16_NLRX1', '16_GCGR', '17_PRRC2C', '17_SSPO', '17_USP2', '17_RAC3', '18_SWT1', '18_OR8G1', '18_FASN', '19_CHI3L1', '19_PATE4', '19_FASN', '20_LYPLAL1', '20_CSNK1D', '21_PARP1', '21_FN3K', '22_LYST', '23_FMN2', '24_SCCPDH', nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
```

**Comment by endrebak** [comment]
This likely means that the series had different indexes:

```
import pandas as pd
s1 = pd.Series("a b c d e".split())
s2 = pd.Series("a b c d e".split(), index=range(2,7))
s1 + "_" + s2
# 0    NaN
# 1    NaN
# 2    c_a
# 3    d_b
# 4    e_c
# 5    NaN
# 6    NaN
# dtype: object
```

Did you just do

```
gr.Name = gr.Name + "whatevz"
```

? If so, it is worrisome that the indexes are not aligned...

If you had some custom code that changed the indexes in some way the above is to be expected.

Remember that pandas always tried to use the indexes to align values before operations. So if pandas does something you think is weird, misaligned indexes are going to be the culprit 99% of the time:

```
import pandas as pd
s3 = pd.Series([1, 2, 3])
s4 = pd.Series([1, 2, 3], index=[2, 1, 0])
s3 + s4
# 0    4
# 1    4
# 2    4
# dtype: int64

# However if you use the underlying, non-indexed numpy array:
s3 + s4.values
0    2
1    4
2    6
dtype: int64
```

**Comment by wdecoster** [comment]
I'm not sure what's going on...
I did a pyranges.sort().merge() on this object, then a .nearest() to get the name back and then assigned to gr.Identifier = pd.Series(np.arange(len(gr))).astype(str) + '-' + gr.Name.astype(str)

For me this is solved now, but if you want to get to the bottom of this I can provide files over email.

**Comment by endrebak** [comment]
Yes please! And the code which produced the behavior. I want pyranges to be
as pain-free as possible.
