### ISSUE TITLE
 join(how="left") error: "TypeError: '(slice(None, None, None), 'Feature')' is an invalid key" 

### ISSUE THREAD

**Issue by SamBryce-Smith** [biocore-ntnu/pyranges#158]
Hi Endre,

I've come across this quirky error when trying to specify *how* for the join function. Weirdly, I could reproduce it for certain combinations of example objects in *pr.data* but not all...

e.g. using *cpg* and *exons*, specifying how = "left" or how = "right" works as expected and doesn't throw an error 
```
import pyranges as pr
cpg = pr.data.cpg()
exons = pr.data.exons()

cpg.join(exons, how="left")
+--------------+-----------+-----------+-----------+-----------+-----------+----------------------------------------+-----------+--------------+
| Chromosome   | Start     | End       | CpG       | Start_b   | End_b     | Name                                   | Score     | Strand       |
| (category)   | (int32)   | (int32)   | (int64)   | (int32)   | (int32)   | (object)                               | (int64)   | (category)   |
|--------------+-----------+-----------+-----------+-----------+-----------+----------------------------------------+-----------+--------------|
| chrX         | 584563    | 585326    | 66        | 585078    | 585337    | NM_000451_exon_0_0_chrX_585079_f       | 0         | +            |
| chrX         | 10094050  | 10094406  | 26        | 10094153  | 10094346  | NM_015691_exon_14_0_chrX_10094154_f    | 0         | +            |
| chrX         | 13587648  | 13588221  | 49        | 13587693  | 13588054  | NM_001167890_exon_0_0_chrX_13587694_f  | 0         | +            |
| chrX         | 17755053  | 17756648  | 117       | 17755568  | 17755800  | NM_001037535_exon_0_0_chrX_17755569_f  | 0         | +            |
| ...          | ...       | ...       | ...       | ...       | ...       | ...                                    | ...       | ...          |
| chrY         | 15591259  | 15591720  | 33        | 15591393  | 15592550  | NR_047610_exon_27_0_chrY_15591394_r    | 0         | -            |
| chrY         | 15591259  | 15591720  | 33        | 15591393  | 15592550  | NR_047607_exon_29_0_chrY_15591394_r    | 0         | -            |
| chrY         | 15591259  | 15591720  | 33        | 15591393  | 15592550  | NM_001258269_exon_29_0_chrY_15591394_r | 0         | -            |
| chrY         | 15591259  | 15591720  | 33        | 15591393  | 15592550  | NR_047599_exon_28_0_chrY_15591394_r    | 0         | -            |
+--------------+-----------+-----------+-----------+-----------+-----------+----------------------------------------+-----------+--------------+
Stranded PyRanges object has 1,084 rows and 9 columns from 2 chromosomes.
For printing, the PyRanges was sorted on Chromosome and Strand.

cpg.join(exons, how="right")
+--------------+-----------+-----------+-----------+-----------+-----------+----------------------------------------+-----------+--------------+
| Chromosome   | Start     | End       | CpG       | Start_b   | End_b     | Name                                   | Score     | Strand       |
| (category)   | (int32)   | (int32)   | (int64)   | (int32)   | (int32)   | (object)                               | (int64)   | (category)   |
|--------------+-----------+-----------+-----------+-----------+-----------+----------------------------------------+-----------+--------------|
| chrX         | 584563    | 585326    | 66        | 585078    | 585337    | NM_000451_exon_0_0_chrX_585079_f       | 0         | +            |
| chrX         | 10094050  | 10094406  | 26        | 10094153  | 10094346  | NM_015691_exon_14_0_chrX_10094154_f    | 0         | +            |
| chrX         | 13587648  | 13588221  | 49        | 13587693  | 13588054  | NM_001167890_exon_0_0_chrX_13587694_f  | 0         | +            |
| chrX         | 17755053  | 17756648  | 117       | 17755568  | 17755800  | NM_001037535_exon_0_0_chrX_17755569_f  | 0         | +            |
| ...          | ...       | ...       | ...       | ...       | ...       | ...                                    | ...       | ...          |
| chrY         | -1        | -1        | -1        | 15409586  | 15409728  | NR_047633_exon_3_0_chrY_15409587_r     | 0         | -            |
| chrY         | -1        | -1        | -1        | 15478146  | 15478273  | NR_047634_exon_18_0_chrY_15478147_r    | 0         | -            |
| chrY         | -1        | -1        | -1        | 15360258  | 15361762  | NR_047601_exon_0_0_chrY_15360259_r     | 0         | -            |
| chrY         | -1        | -1        | -1        | 15467254  | 15467278  | NM_001258270_exon_13_0_chrY_15467255_r | 0         | -            |
+--------------+-----------+-----------+-----------+-----------+-----------+----------------------------------------+-----------+--------------+
Stranded PyRanges object has 1,001 rows and 9 columns from 2 chromosomes.
For printing, the PyRanges was sorted on Chromosome and Strand.

```

If I use *gencode_gtf* and *chipseq*, default join (i.e. how = None) works as intended, but specifying how = "left" or how = "right" produces the following error (same  error I got in my own use case with object derived from a full GENCODE GTF file).

```
gencode_gtf = pr.data.gencode_gtf()
chipseq = pr.data.chipseq()

#join with default settings works fine
gencode_gtf.join(chipseq)
+--------------+------------+--------------+-----------+-----------+------------+--------------+------------+-------------------+----------------+-------------+------------+----------------------+-------+
| Chromosome   | Source     | Feature      |     Start |       End | Score      | Strand       | Frame      | gene_id           | gene_type      | gene_name   |      level | havana_gene          | +16   |
| (category)   | (object)   | (category)   |   (int32) |   (int32) | (object)   | (category)   | (object)   | (object)          | (object)       | (object)    |   (object) | (object)             | ...   |
|--------------+------------+--------------+-----------+-----------+------------+--------------+------------+-------------------+----------------+-------------+------------+----------------------+-------|
| chr1         | HAVANA     | gene         |   1324755 |   1328897 | .          | +            | .          | ENSG00000224051.6 | protein_coding | CPTP        |          2 | OTTHUMG00000003171.3 | ...   |
| chr1         | HAVANA     | transcript   |   1324755 |   1327994 | .          | +            | .          | ENSG00000224051.6 | protein_coding | CPTP        |          2 | OTTHUMG00000003171.3 | ...   |
| chr1         | HAVANA     | transcript   |   1324766 |   1328897 | .          | +            | .          | ENSG00000224051.6 | protein_coding | CPTP        |          2 | OTTHUMG00000003171.3 | ...   |
| chr1         | HAVANA     | transcript   |   1325240 |   1327471 | .          | +            | .          | ENSG00000224051.6 | protein_coding | CPTP        |          2 | OTTHUMG00000003171.3 | ...   |
| chr1         | HAVANA     | exon         |   1325240 |   1325595 | .          | +            | .          | ENSG00000224051.6 | protein_coding | CPTP        |          2 | OTTHUMG00000003171.3 | ...   |
| chr1         | HAVANA     | UTR          |   1325240 |   1325595 | .          | +            | .          | ENSG00000224051.6 | protein_coding | CPTP        |          2 | OTTHUMG00000003171.3 | ...   |
+--------------+------------+--------------+-----------+-----------+------------+--------------+------------+-------------------+----------------+-------------+------------+----------------------+-------+
Stranded PyRanges object has 6 rows and 29 columns from 1 chromosomes.
For printing, the PyRanges was sorted on Chromosome and Strand.
16 hidden columns: transcript_id, transcript_type, transcript_name, transcript_support_level, tag, havana_transcript, exon_number, exon_id, ont, protein_id, ccdsid, Start_b, End_b, Name, Score_b, Strand_b


gencode_gtf.join(chipseq, how = "left")

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sam/miniconda3/envs/single_utrs/lib/python3.8/site-packages/pyranges/pyranges.py", line 2144, in join
    dfs = pyrange_apply(_write_both, self, other, **kwargs)
  File "/home/sam/miniconda3/envs/single_utrs/lib/python3.8/site-packages/pyranges/multithreaded.py", line 291, in pyrange_apply
    result = call_f(function, nparams, df, odf, kwargs)
  File "/home/sam/miniconda3/envs/single_utrs/lib/python3.8/site-packages/pyranges/multithreaded.py", line 23, in call_f
    return f.remote(df, odf, **kwargs)
  File "/home/sam/miniconda3/envs/single_utrs/lib/python3.8/site-packages/pyranges/methods/join.py", line 127, in _write_both
    scdf, ocdf = _both_dfs(scdf, ocdf, how=how)
  File "/home/sam/miniconda3/envs/single_utrs/lib/python3.8/site-packages/pyranges/methods/join.py", line 80, in _both_dfs
    sh = null_types(scdf.head(1))
  File "/home/sam/miniconda3/envs/single_utrs/lib/python3.8/site-packages/pyranges/methods/join.py", line 66, in null_types
    h2.loc[:, n] = h2[:, n].cat.add_categories("-1")
  File "/home/sam/miniconda3/envs/single_utrs/lib/python3.8/site-packages/pandas/core/frame.py", line 2902, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/sam/miniconda3/envs/single_utrs/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 2895, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 75, in pandas._libs.index.IndexEngine.get_loc
TypeError: '(slice(None, None, None), 'Feature')' is an invalid key

#using how="right" returns same error

```

Any ideas for solving this? If it helps, in my own use case, I'm using a pyranges object from a gencode GTF (read in with *read_gtf*).

For current project, I'm using using a conda environment with following versions (Happy to share environment YAML file if you want it):
python 3.8.6
pyranges 0.0.86
pandas 1.1.3

(For what it's worth, I had a conda environment from a previous project with python 3.6.10, pyranges 0.0.77 & pandas 1.0.3 and the behaviour was exactly the same, perhaps a pandas 1.x problem?)

Thanks for your time and for developing the package, it's great (along with plyranges in R, integrating genomics operations with existing data science ecosystems is so handy!).

Cheers,
Sam

**Comment by endrebak** [comment]
Thanks for reporting this!

I doubt it is a pandas 1.0-issue. I suspect that these options have not been much used and hence might contain a few bugs.

I will have to look at join right and left. I'll try to make a reproducible example.

**Comment by endrebak** [comment]
I found the bug and will upload a fix after the tests have passed.

This reminded me of another thing: most functionality in pyranges is tested thoroughly by comparing it with bedtools, but join with left/right is currently not tested. I should find the relevant functions in bedtools and add the appropriate tests for join left/right.

**Comment by SamBryce-Smith** [comment]
Amazing thanks for the speedy response and fix!

**Comment by endrebak** [comment]
Now it should be out on pypi :) I fear there are more bugs in the left/right-options. I will try to add a test for them soon :)

**Comment by endrebak** [comment]
Now 0.0.87 should be out on pypi :) I fear there are more bugs in the left/right-options. I will try to add a test for them soon :)
