### ISSUE TITLE
const int32_t' but got 'long' when joining two bed files

### ISSUE THREAD

**Issue by akmorrow13** [biocore-ntnu/pyranges#170]
When I try to load two bed files using `read_bed` , then run a left join `res = bed1.join(bed2, how='left')` I get the following error:

` ValueError: Buffer dtype mismatch, expected 'const int32_t' but got 'long'`

**Comment by endrebak** [comment]
Thanks for reporting! Can you look in the headers and confirm that one is int64 and one is int32?

**Comment by akmorrow13** [comment]
Fix: specify` int64=True` when loading in a pyranges object from DataFrame:` pr.PyRanges(df, int64=True)`

**Comment by akmorrow13** [comment]
Hi @endrebak! Do you mean the bed file headers? In this case, neither bed file has a header. One of the bed files is just a test file (3 lines, no header). The other file is gzipped, but has no header unzipped.

**Comment by endrebak** [comment]
I meant that if you print the pyranges you will see their types in the
headers :)

Thanks for reporting btw

**Comment by akmorrow13** [comment]
Ah, apologies! They both have int32 for start and end. See screenshot below:
![Screen Shot 2021-01-26 at 9 38 52 AM](https://user-images.githubusercontent.com/6503416/105867184-6819a900-5fba-11eb-9eef-f0056aebe1a4.png)

**Comment by endrebak** [comment]
Would you be able to share these files with me so I can try to reproduce
the bug? I am always eager to submit fixes.

**Comment by akmorrow13** [comment]
Of course! Attached are a compressed folder of the two bed files and pip freeze. I included the pip freeze file because this issue only occurs on some of my virtual environments (not all).I tried matching the ncls and pyranges versions in the working environment (ncls 0.0.53, pyranges 0.0.84) but this did not solve the issue.


[files_issue170.zip](https://github.com/biocore-ntnu/pyranges/files/5880677/files_issue170.zip)

**Comment by endrebak** [comment]
These are the contents:

```
ls -latrh *
-rw-r--r--@ 1 endrebakkenstovner  staff   263K Jan 27 04:11 test.zip
-rw-------@ 1 endrebakkenstovner  staff   5.6K Jan 27 14:55 all.pos.bed.gz
-rw-------@ 1 endrebakkenstovner  staff   1.8K Jan 27 14:59 pip_freeze.txt

test:
total 600
-rw-r--r--@ 1 endrebakkenstovner  staff   297K Jan 27 04:10 data.h5
drwxr-xr-x@ 3 endrebakkenstovner  staff    96B Jan 27 04:10 ./
drwxr-xr-x@ 6 endrebakkenstovner  staff   192B Jan 27 16:42 ../
```

It seems to be missing one bed file :) I tried reading the `.h5`, but got the error

```
----> 1 pd.read_hdf("test/data.h5")

~/anaconda3/lib/python3.8/site-packages/pandas/io/pytables.py in read_hdf(path_or_buf, key, mode, errors, where, start, stop, columns, iterator, chunksize, **kwargs)
    404             groups = store.groups()
    405             if len(groups) == 0:
--> 406                 raise ValueError("No dataset in HDF5 file.")
    407             candidate_only_group = groups[0]
    408

ValueError: No dataset in HDF5 file.
```

**Comment by akmorrow13** [comment]
Sorry, I must have zipped the wrong file. It should include two bed files (1 gzipped).
[files_issue170.zip](https://github.com/biocore-ntnu/pyranges/files/5881324/files_issue170.zip)

**Comment by endrebak** [comment]
Can't reproduce, but perhaps the stack trace could be of help :) Do you have it?

Also, please look for any weirdness when using "left", "right". I do not know if these flags have been used much :)

**Comment by endrebak** [comment]
Thanks for the prompt upload btw

**Comment by akmorrow13** [comment]
Here is the stack trace:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/yosef2/users/akmorrow/miniconda3/envs/EpitomeVersionTest/lib/python3.7/site-packages/pyranges/pyranges.py", line 2144, in join
    dfs = pyrange_apply(_write_both, self, other, **kwargs)
  File "/data/yosef2/users/akmorrow/miniconda3/envs/EpitomeVersionTest/lib/python3.7/site-packages/pyranges/multithreaded.py", line 304, in pyrange_apply
    result = call_f(function, nparams, df, odf, kwargs)
  File "/data/yosef2/users/akmorrow/miniconda3/envs/EpitomeVersionTest/lib/python3.7/site-packages/pyranges/multithreaded.py", line 23, in call_f
    return f.remote(df, odf, **kwargs)
  File "/data/yosef2/users/akmorrow/miniconda3/envs/EpitomeVersionTest/lib/python3.7/site-packages/pyranges/methods/join.py", line 127, in _write_both
    scdf, ocdf = _both_dfs(scdf, ocdf, how=how)
  File "/data/yosef2/users/akmorrow/miniconda3/envs/EpitomeVersionTest/lib/python3.7/site-packages/pyranges/methods/join.py", line 76, in _both_dfs
    _self_indexes, _other_indexes = _both_indexes(scdf, ocdf, how)
  File "/data/yosef2/users/akmorrow/miniconda3/envs/EpitomeVersionTest/lib/python3.7/site-packages/pyranges/methods/join.py", line 33, in _both_indexes
    starts, ends, indexes)
  File "ncls/src/ncls.pyx", line 75, in ncls.src.ncls.NCLS64.all_overlaps_both
ValueError: Buffer dtype mismatch, expected 'const int64_t' but got 'int'
```

**Comment by ttbond** [comment]
Met exactly the same problem in left join! Looking forward a further updating!

**Comment by endrebak** [comment]
I will look at this tomorrow
