### ISSUE TITLE
expected 'const int64_t' but got 'int'

### ISSUE THREAD

**Issue by fakedrtom** [biocore-ntnu/pyranges#177]
I have integrated pyranges into some tools that I have been developing that take a VCF and convert genomic coordinates into pyranges objects to perform certain tasks. Previously I had a conda env with pyranges 0.0.79 and never had any trouble with it. Recently I created a new conda env and downloaded the latest pyranges for it (0.0.93). I am now getting this error with certain VCFs:

ValueError: Buffer dtype mismatch, expected 'const int64_t' but got 'int'

which I believe is being triggered by the following:

joined = pr_vcf.join(pr_bed, how = "left").sort()

If I revert to my older env (0.0.79) I do not get this error, even with the same VCF. After digging around a little bit, I think the error in 0.0.93 may be related to non-canonical chromosome types (e.g. chr5_GL000208v1_random or chrUn_JTFH01000165v1_decoy). I am not positive this is the case, but when I remove these chromosomes from my VCF, the pyranges performs as expected. Perhaps the latest version of pyranges has some sort of casting problem?

**Comment by fakedrtom** [comment]
Very strange. I just tried doing the exact some thing as you and I do produce the error:

```gr.join(gr2, how="left")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/scratch/ucgd/lustre/work/u0055382/miniconda/envs/svafotate-new/lib/python3.8/site-packages/pyranges/pyranges.py", line 2144, in join
    dfs = pyrange_apply(_write_both, self, other, **kwargs)
  File "/scratch/ucgd/lustre/work/u0055382/miniconda/envs/svafotate-new/lib/python3.8/site-packages/pyranges/multithreaded.py", line 305, in pyrange_apply
    result = call_f(function, nparams, df, odf, kwargs)
  File "/scratch/ucgd/lustre/work/u0055382/miniconda/envs/svafotate-new/lib/python3.8/site-packages/pyranges/multithreaded.py", line 22, in call_f
    return f.remote(df, odf, **kwargs)
  File "/scratch/ucgd/lustre/work/u0055382/miniconda/envs/svafotate-new/lib/python3.8/site-packages/pyranges/methods/join.py", line 129, in _write_both
    scdf, ocdf = _both_dfs(scdf, ocdf, how=how)
  File "/scratch/ucgd/lustre/work/u0055382/miniconda/envs/svafotate-new/lib/python3.8/site-packages/pyranges/methods/join.py", line 78, in _both_dfs
    _self_indexes, _other_indexes = _both_indexes(scdf, ocdf, how)
  File "/scratch/ucgd/lustre/work/u0055382/miniconda/envs/svafotate-new/lib/python3.8/site-packages/pyranges/methods/join.py", line 32, in _both_indexes
    _self_indexes, _other_indexes = it.all_overlaps_both(
  File "ncls/src/ncls.pyx", line 75, in ncls.src.ncls.NCLS64.all_overlaps_both
ValueError: Buffer dtype mismatch, expected 'const int64_t' but got 'int'```

**Comment by endrebak** [comment]
Pip install —upgrade ncls? If that does not work I’ll have a look tomorrow:)

**Comment by fakedrtom** [comment]
Thanks for taking to time to work on this with me. 

I checked and my ncls is already running the latest version (0.0.57). I also tried updating pyranges to the latest version (0.0.95) and repeated what I previously did with the examples you tried above and I am still getting the same error.

**Comment by fakedrtom** [comment]
Sorry this took me a little while. These are generating the error for me (had to add txt to the filename to upload here, but you can change the name if necessary):

[bed_sample.bed.txt](https://github.com/biocore-ntnu/pyranges/files/6125201/bed_sample.bed.txt)
[vcf_sample.bed.txt](https://github.com/biocore-ntnu/pyranges/files/6125204/vcf_sample.bed.txt)

**Comment by endrebak** [comment]
This sequence of commands does not error on my end:

```
import pyranges as pr
b = pr.read_bed("bed_sample.bed.txt")
v = pr.read_bed("vcf_sample.bed.txt")
v.join(b, how="left").sort()
import pandas as pd
pd.__version__
```

I am still eager to help though.

What if you convert the `Start` and `End` columns to `int64` first? 

```
b = pr.PyRanges(b.df.astype({"Start": np.int64, "End": np.int64}), int64=True)
v = pr.PyRanges(v.df.astype({"Start": np.int64, "End": np.int64}), int64=True)
```

**Comment by fakedrtom** [comment]
Converting to int64 appears to do the trick. I tested it out on the original VCF that was causing my problems and it completed without any error. But I am puzzled why you could not produce the error. There must be something different in my env.

**Comment by endrebak** [comment]
I would like to help out, but cannot reproduce. Perhaps someone else will report something similar and I'll be able to triangulate :)

**Comment by wdecoster** [comment]
Hi @endrebak,

I seem to get the same error, raised from https://github.com/wdecoster/methplotlib/blob/master/methplotlib/differential/differential.py#L34

```
Traceback (most recent call last):
  File "/home/wdecoster/repositories/methplotlib/scripts/allele_specific_modification", line 28, in <module>
    result = main(gr, gr2, bed)
  File "/home/wdecoster/repositories/methplotlib/methplotlib/differential/differential.py", line 52, in main
    m = merge_regions_with_bed(bed, a, b)
  File "/home/wdecoster/repositories/methplotlib/methplotlib/differential/differential.py", line 34, in merge_regions_with_bed
    a = bed.join(a, how="left").apply(count_total_and_methylated).drop(like="_b")
  File "/home/wdecoster/miniconda3/envs/meth/lib/python3.7/site-packages/pyranges/pyranges.py", line 2153, in join
    dfs = pyrange_apply(_write_both, self, other, **kwargs)
  File "/home/wdecoster/miniconda3/envs/meth/lib/python3.7/site-packages/pyranges/multithreaded.py", line 251, in pyrange_apply
    result = call_f(function, nparams, df, odf, kwargs)
  File "/home/wdecoster/miniconda3/envs/meth/lib/python3.7/site-packages/pyranges/multithreaded.py", line 22, in call_f
    return f.remote(df, odf, **kwargs)
  File "/home/wdecoster/miniconda3/envs/meth/lib/python3.7/site-packages/pyranges/methods/join.py", line 129, in _write_both
    scdf, ocdf = _both_dfs(scdf, ocdf, how=how)
  File "/home/wdecoster/miniconda3/envs/meth/lib/python3.7/site-packages/pyranges/methods/join.py", line 78, in _both_dfs
    _self_indexes, _other_indexes = _both_indexes(scdf, ocdf, how)
  File "/home/wdecoster/miniconda3/envs/meth/lib/python3.7/site-packages/pyranges/methods/join.py", line 33, in _both_indexes
    starts, ends, indexes)
  File "ncls/src/ncls.pyx", line 75, in ncls.src.ncls.NCLS64.all_overlaps_both
ValueError: Buffer dtype mismatch, expected 'const int64_t' but got 'int'
```

I'll send you an email with the files that cause this error.

Cheers,
Wouter
