### ISSUE TITLE
IndexError when using count_overlaps

### ISSUE THREAD

**Issue by charlotte-west** [biocore-ntnu/pyranges#184]
Hi, I am trying to count the number of aligned fragments that occur in called peaks by overlapping aligned fragments from a bam file with peaks from a bed file. I read those in to data frames and then create pyranges objects with them:

```
sample_id = 'h3k27me3_R1'
pyr_seacr = pr.PyRanges(chromosomes=seacr_bed_i['chrom'], starts=seacr_bed_i['start'], ends=seacr_bed_i['end'])
pyr_bam = pr.PyRanges(df=bam_i)
pyr_bam_dict = {sample_id : pyr_bam}
```

This step seems successful, as when I print I get:

```
print(pyr_bam_dict)
print(pyr_seacr)

{'h3k27me3_R1': +--------------+-----------+-----------+--------------+------------+
| Chromosome   | Start     | End       | Strand       | Flag       |
| (category)   | (int32)   | (int32)   | (category)   | (uint16)   |
|--------------+-----------+-----------+--------------+------------|
| chr1         | 10410     | 10435     | +            | 83         |
| chr1         | 31292     | 31315     | +            | 83         |
| chr1         | 57460     | 57485     | +            | 147        |
| chr1         | 91169     | 91194     | +            | 147        |
| ...          | ...       | ...       | ...          | ...        |
| chrY         | 56835550  | 56835575  | -            | 99         |
| chrY         | 56842707  | 56842730  | -            | 163        |
| chrY         | 56855765  | 56855790  | -            | 99         |
| chrY         | 56863334  | 56863358  | -            | 163        |
+--------------+-----------+-----------+--------------+------------+
Stranded PyRanges object has 5,552,966 rows and 5 columns from 113 chromosomes.
For printing, the PyRanges was sorted on Chromosome and Strand.}
+--------------+-----------+-----------+
| Chromosome   | Start     | End       |
| (category)   | (int32)   | (int32)   |
|--------------+-----------+-----------|
| chr1         | 388639    | 388687    |
| chr1         | 393785    | 393833    |
| chr1         | 393974    | 394007    |
| chr1         | 396145    | 396182    |
| ...          | ...       | ...       |
| chrY         | 24325979  | 24326019  |
| chrY         | 25314241  | 25314300  |
| chrY         | 25326416  | 25326463  |
| chrY         | 26482440  | 26482484  |
+--------------+-----------+-----------+
Unstranded PyRanges object has 753,256 rows and 3 columns from 72 chromosomes.
For printing, the PyRanges was sorted on Chromosome.

```

However when I do `frag_count_pyr = pr.count_overlaps(pyr_bam_dict, pyr_seacr)` I get the error message:

```
Traceback (most recent call last):
  File "/home/repo/bin/python/reporting/main.py", line 72, in <module>
    parsed_args.func(parsed_args)
  File "/home/repo/bin/python/reporting/main.py", line 44, in gen_png
    fig.gen_plots_to_folder(output_path)
  File "/home/repo/bin/python/reporting/lib/figures.py", line 316, in gen_plots_to_folder
    plots, data = self.generate_plots()
  File "/home/repo/bin/python/reporting/lib/figures.py", line 240, in generate_plots
    self.load_data()
  File "/home/repo/bin/python/reporting/lib/figures.py", line 222, in load_data
    frag_count_pyr = pr.count_overlaps(pyr_bam_dict, pyr_seacr)
  File "/opt/conda/envs/reporting/lib/python3.8/site-packages/pyranges/multioverlap.py", line 150, in count_overlaps
    res = features.apply_pair(gr, _count_overlaps, **kwargs)
  File "/opt/conda/envs/reporting/lib/python3.8/site-packages/pyranges/pyranges.py", line 775, in apply_pair
    result = pyrange_apply(f, self, other, **kwargs)
  File "/opt/conda/envs/reporting/lib/python3.8/site-packages/pyranges/multithreaded.py", line 268, in pyrange_apply
    result = call_f(function, nparams, df, odf, kwargs)
  File "/opt/conda/envs/reporting/lib/python3.8/site-packages/pyranges/multithreaded.py", line 22, in call_f
    return f.remote(df, odf, **kwargs)
  File "/opt/conda/envs/reporting/lib/python3.8/site-packages/pyranges/methods/intersection.py", line 106, in _count_overlaps
    sx.iloc[vc.index, 0] = vc.values
  File "/opt/conda/envs/reporting/lib/python3.8/site-packages/pandas/core/indexing.py", line 692, in __setitem__
    iloc._setitem_with_indexer(indexer, value, self.name)
  File "/opt/conda/envs/reporting/lib/python3.8/site-packages/pandas/core/indexing.py", line 1637, in _setitem_with_indexer
    self._setitem_single_block(indexer, value, name)
  File "/opt/conda/envs/reporting/lib/python3.8/site-packages/pandas/core/indexing.py", line 1861, in _setitem_single_block
    self.obj._mgr = self.obj._mgr.setitem(indexer=indexer, value=value)
  File "/opt/conda/envs/reporting/lib/python3.8/site-packages/pandas/core/internals/managers.py", line 568, in setitem
    return self.apply("setitem", indexer=indexer, value=value)
  File "/opt/conda/envs/reporting/lib/python3.8/site-packages/pandas/core/internals/managers.py", line 427, in apply
    applied = getattr(b, f)(**kwargs)
  File "/opt/conda/envs/reporting/lib/python3.8/site-packages/pandas/core/internals/blocks.py", line 1029, in setitem
    values[indexer] = value
IndexError: index 344275 is out of bounds for axis 0 with size 1
```
Thank you in advance for taking a look!

**Comment by charlotte-west** [comment]
^sorry, accidentally trigger happy when trying to upload the example data!

**Comment by charlotte-west** [comment]
[test_bam_1.csv.gz](https://github.com/biocore-ntnu/pyranges/files/6404872/test_bam_1.csv.gz)
[test_bam_2.csv.gz](https://github.com/biocore-ntnu/pyranges/files/6404874/test_bam_2.csv.gz)
[test_bam_3.csv.gz](https://github.com/biocore-ntnu/pyranges/files/6404875/test_bam_3.csv.gz)
[test_bam_4.csv.gz](https://github.com/biocore-ntnu/pyranges/files/6404876/test_bam_4.csv.gz)
[test_bed.csv.gz](https://github.com/biocore-ntnu/pyranges/files/6404877/test_bed.csv.gz)

**Comment by charlotte-west** [comment]
I installed a live version of the code to see if I could do some debugging. It looks to me to be an error that would occur when the pyranges objects have ranges for more than one chromosome (indeed it works when I do count_overlaps for only one chromosome but errors for data with multiple). I have got it to run by replacing line 106 in intersection.py from

```
sx.iloc[vc.index, 0] = vc.values
```

to 

```
sx.iloc[(vc.index - vc.index[0]), 0] = vc.values
```

It produces a reasonable looking result, but perhaps this attempted fix is wreaking havoc somewhere else that I cannot see!

**Comment by endrebak** [comment]
Weird. It was not that fragile before. Perhaps pandas has changed
underneath? Will investigate.

**Comment by endrebak** [comment]
Have you tried pyr_bam.count_overlaps(pyr_seacr) ? :)

If you do help in the REPL you'll see docs with examples.

help(pr.count_overlaps)

help(pyr_bam.count_overlaps)

Tell me if the above suggestion does not work :)

**Comment by charlotte-west** [comment]
Yes it looks like that has worked, thank you! Sorry, I should have seen that syntax. I was going off of another syntax that I saw in the documentation ```pr.count_overlaps(grs, gr)```. Thanks again!

**Comment by endrebak** [comment]
No problem. Learning a new API is difficult :)
