### ISSUE TITLE
[Bug report] kwargs 'invert

### ISSUE THREAD

**Issue by zztin** [biocore-ntnu/pyranges#200]
Hi,
I found some errors occur only after specifying nb_cpu, and will retain fail after trying specifying nb_cpu (in Jupyter notebook). Could be related to some automatic detection of parameters.
Steps to reproduce:
1. Launch Jupyter notebook
2. initialise example data:
Example data:
```
a = '''Chromosome Start End Strand
... chr1    10008    10200 +
... chr1    111499    121499 - 
... chr1    22    27 - 
... chr2    24    30 - '''
b = '''Chromosome Start End
... chr2    12    32
... chr2    14    35240'''
c = '''Chromosome Start End
... chr2    8    15
... chr2    713800    714800
... chr2    32    34'''
example_grs = {n: pr.from_string(s) for n, s in zip(["a", "b", "c"], [a, b, c])}
example_grs
```
3. `overlap = pr.count_overlaps(example_grs, example_grs['c'])`
4. Above would return correct overlap PyRanges.
5. overlap = pr.count_overlaps(example_grs, example_grs['c'], nb_cpu = 2)
6. Return error:
```
RayTaskError(KeyError): ray::_count_overlaps() (pid=95889, ip=192.168.68.103)
  File "python/ray/_raylet.pyx", line 501, in ray._raylet.execute_task
  File "/Users/lchen/miniconda/envs/nb/lib/python3.8/site-packages/ray/util/tracing/tracing_helper.py", line 330, in _function_with_tracing
    return function(*args, **kwargs)
  File "/Users/lchen/miniconda/envs/nb/lib/python3.8/site-packages/pyranges/methods/intersection.py", line 98, in _count_overlaps
    idx = _overlap(scdf, ocdf, **kwargs)
  File "/Users/lchen/miniconda/envs/nb/lib/python3.8/site-packages/pyranges/methods/intersection.py", line 64, in _overlap
    invert = kwargs["invert"]
KeyError: 'invert'
```
7. The same command failed again after removing the parameter (in Jupyter notebook):
`overlap = pr.count_overlaps(example_grs, example_grs['c'])`

```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-7-bbc720a5d4be> in <module>
----> 1 overlap = pr.count_overlaps(example_grs, example_grs['c'])
      2 

~/miniconda/envs/nb/lib/python3.8/site-packages/pyranges/multioverlap.py in count_overlaps(grs, features, strandedness, how, nb_cpu)
    148         gr = gr.drop()
    149 
--> 150         res = features.apply_pair(gr, _count_overlaps, **kwargs)
    151 
    152         setattr(features, name, res)

~/miniconda/envs/nb/lib/python3.8/site-packages/pyranges/pyranges.py in apply_pair(self, other, f, strandedness, as_pyranges, **kwargs)
    773         kwargs = fill_kwargs(kwargs)
    774 
--> 775         result = pyrange_apply(f, self, other, **kwargs)
    776 
    777         if not as_pyranges:

~/miniconda/envs/nb/lib/python3.8/site-packages/pyranges/multithreaded.py in pyrange_apply(function, self, other, **kwargs)
    266                 df, odf = make_binary_sparse(kwargs, df, odf)
    267 
--> 268                 result = call_f(function, nparams, df, odf, kwargs)
    269                 results.append(result)
    270 

~/miniconda/envs/nb/lib/python3.8/site-packages/pyranges/multithreaded.py in call_f(f, nparams, df, odf, kwargs)
     22         return f.remote(df, odf, **kwargs)
     23     else:
---> 24         return f.remote(df, odf)
     25 
     26 

~/miniconda/envs/nb/lib/python3.8/site-packages/pyranges/methods/intersection.py in _count_overlaps(scdf, ocdf, **kwargs)
     96 
     97     kwargs["return_indexes"] = True
---> 98     idx = _overlap(scdf, ocdf, **kwargs)
     99 
    100     sx = pd.DataFrame(np.zeros(len(scdf)), index=scdf.index)

~/miniconda/envs/nb/lib/python3.8/site-packages/pyranges/methods/intersection.py in _overlap(scdf, ocdf, **kwargs)
     62 def _overlap(scdf, ocdf, **kwargs):
     63 
---> 64     invert = kwargs["invert"]
     65     return_indexes = kwargs.get("return_indexes", False)
     66 

KeyError: 'invert'
```

**Comment by endrebak** [comment]
Will look at now. Thanks for reporting.

**Comment by endrebak** [comment]
I think the Ray module has changed a lot. It does not even work on my M1 MacBook air.
