### ISSUE TITLE
Subtract over 1024 pyranges gives weird results

### ISSUE THREAD

**Issue by MateuszChilinski** [biocore-ntnu/pyranges#220]
Hey,

I noticed that if I have 2 sets of pyranges, and one is uniform (e.g. 0 to 100 000 000), when I subtract more than 1024 pyranges (all in between 0 to that 100 000 000), I receive some weird results - e.g. length of such subtraction is around twice over 100 000 000.

I attach mock file with data & script presenting the bug.

`import pandas as pd
import pyranges as pr

data = pd.read_csv('data.csv')
uniform_set = pr.PyRanges(pd.DataFrame({"Chromosome": [data["Chromosome"][0]], "Start": [min(data["Start"])], "End": [max(data["End"])]}))
data = pr.PyRanges(data)
data_sub = uniform_set.subtract(data)

print(data_sub.summary())`

[data.csv](https://github.com/biocore-ntnu/pyranges/files/7144979/data.csv)

**Comment by endrebak** [comment]
Wonderful! Thanks for the bughunting. Since the number 1024 pops up I wonder if the bug isn’t due to the C-implementation of the NCLS. There the number 1024 is magical: https://github.com/biocore-ntnu/ncls/blob/14ee35bf183096b7b1a94ff1f2bb826da52e4aeb/ncls/src/ncls32.pyx#L496

**Comment by endrebak** [comment]
I will look at it tomorrow

**Comment by endrebak** [comment]
I think I see one error already and how to fix it. When writing high-performance C-code it is so easy to forget details. I dunno if it is related to the bug you found.

The error is I see is that if one interval has more than 1024 overlaps, it does not search for more than 1024. I do not understand the error you posted since I do not have access to a computer

**Comment by MateuszChilinski** [comment]
It's fine, I made a hotfix and delete max 1024 ranges, then next 1024 etc.
I just posted the issue for further development :)

**Comment by endrebak** [comment]
I think I am going to be able to fix all the 1024-errors today... except perhaps for subtract, the exact one you wanted fixed XD. 

In its current implementation, it is a more involved algorithm, plain and simple. I'll look into simplifying it and then fixing the error.

**Comment by endrebak** [comment]
I think I have it but want to sleep on it until tomorrow.

**Comment by MateuszChilinski** [comment]
It's always best to sleep on the problem :-) usually, the simplest and most efficient solutions come around then!

**Comment by endrebak** [comment]
This is my attempt:

```
#!/usr/bin/env python

import pandas as pd
import numpy as np

import pyranges as pr

gr = pr.from_string("""Chromosome Start End
chr1 1 100
chr2 1 100
chr3 1 100
chr4 10 90
chr5 10 100
""")

gr2 = pr.from_string("""Chromosome Start End
chr1 5 10
chr1 15 20
chr1 30 50
chr1 90 95
chr2 0 10
chr2 15 20
chr2 30 50
chr2 90 105
chr3 0 105
chr4 0 20
chr5 90 105
""")

def add_rows_per_group(df):
    last_rows = df.groupby("__ix__").last().reset_index()
    last_rows.loc[:, "__last__"] = True
    df = pd.concat([df, last_rows], ignore_index=True)
    df = df.sort_values("__ix__", ascending=True)
    return df

def new_subtract(gr, gr2):
    falses = np.zeros(len(gr), dtype=bool)
    gr.__ix__ = np.arange(len(gr))
    gr.__first__ = falses
    gr.__last__ = falses

    df = gr.join(gr2).df

    df.insert(df.shape[1], "NewStart", df.End_b.shift(fill_value=-1))
    df.insert(df.shape[1], "NewEnd", df.Start_b)
    df.insert(df.shape[1], "__ix2__", np.arange(len(df)))

    df = add_rows_per_group(df)

    g = df.groupby(df.__ix__, as_index=False)
    first_rows = g.first()
    df.loc[first_rows.__ix2__, "__first__"] = True

    change_start_mask = df.__first__ & (df.Start_b > df.Start)
    if change_start_mask.any():
        df.loc[:, "NewStart"] = np.where(df.__first__, df.Start, df.NewStart)

    df.loc[df.__first__ & ~(df.Start_b > df.Start), "NewStart"] = -1

    change_end_mask = df.__last__ & (df.End_b < df.End)

    if change_end_mask.sum():
        df.loc[:, "NewEnd"] = np.where(df.__last__, df.End, df.NewEnd)
        df.loc[:, "NewStart"] = np.where(df.__last__, df.End_b, df.NewStart)
    df.loc[df.__last__ & ~(df.End_b < df.End), ["NewEnd", "NewStart"]] = -1
    df = df[~((df.NewStart == -1) | (df.NewEnd == -1))]
    df = df.drop(["Start", "End"], axis=1)
    df.rename(columns={"NewStart": "Start", "NewEnd": "End"}, inplace=True)

    df = df.drop(["__ix__", "__ix2__", "__first__", "__last__", "Start_b", "End_b"], axis=1)

    return pr.PyRanges(df)

res = new_subtract(gr, gr2)
print(res.df)
#  Chromosome  Start  End
# 0       chr1      1    5
# 1       chr1     10   15
# 2       chr1     20   30
# 3       chr1     50   90
# 4       chr1     95  100
# 5       chr2     10   15
# 6       chr2     20   30
# 7       chr2     50   90
# 8       chr4     20   90
# 9       chr5     10   90

```

Here is an all-pandas solution. Feel free to try it. Will merge tomorrow and see if the tests pass :)

**Comment by endrebak** [comment]
Now I've started running the tests :) Will see if they pass.

**Comment by endrebak** [comment]
0.0.109 is out. Please tell me if subtract works as expected.

**Comment by MateuszChilinski** [comment]
Sure, I'll get back to it next week though because I'm out of the office :)

**Comment by MateuszChilinski** [comment]
Hey,

I don't think the issue is solved, even quite the opposite. In the example I provided, the interval is 1.33342e+08 bps (sum), and after subtraction of the other intervals from that one large one, I get interval of 5.67278e+08 bps, which is impossible.

**Comment by endrebak** [comment]
You are correct. I did not test on your data, I just got hypothesis to test a lot of smaller cases and saw that my new function produced the same result as bedtools subtract. I'll get around to fixing this

**Comment by endrebak** [comment]
Thanks for testing. I think I have a solution. I'll test it with your data too this time.

**Comment by endrebak** [comment]
Now it passes all my tests and seems to work on your data. I am pretty sure it is all good then. Would love if you could try again :)

**Comment by MateuszChilinski** [comment]
Hey,

I am getting error:

```
Traceback (most recent call last):
  File "/mnt/raid/example_crash.py", line 7, in <module>
    data_sub = uniform_set.subtract(data)
  File "/home/mchilinski/anaconda3/lib/python3.8/site-packages/pyranges/pyranges.py", line 4388, in subtract
    result = pyrange_apply(_subtraction, self, other_clusters, **kwargs)
  File "/home/mchilinski/anaconda3/lib/python3.8/site-packages/pyranges/multithreaded.py", line 305, in pyrange_apply
    result = call_f(function, nparams, df, odf, kwargs)
  File "/home/mchilinski/anaconda3/lib/python3.8/site-packages/pyranges/multithreaded.py", line 22, in call_f
    return f.remote(df, odf, **kwargs)
  File "/home/mchilinski/anaconda3/lib/python3.8/site-packages/pyranges/methods/subtraction.py", line 64, in _subtraction
    idx_self, new_starts, new_ends = o.set_difference_helper(
  File "ncls/src/ncls32.pyx", line 447, in ncls.src.ncls32.NCLS32.set_difference_helper
TypeError: set_difference_helper() takes exactly 3 positional arguments (4 given)
```

**Comment by endrebak** [comment]
Oh, you need to update to the newest NCLS package too. I should add a
requirement on the version in pyranges.

**Comment by MateuszChilinski** [comment]
Works like a charm now :) Thanks for the fixes and for this awesome package! I'm closing the issue now.
