### ISSUE TITLE
read_gtf error if attribute value is empty string (i.e. <key> "";)

### ISSUE THREAD

**Issue by SamBryce-Smith** [biocore-ntnu/pyranges#254]
In an analysis I added a column to a PyRanges object that contained a mix of empty and non-empty strings. I could write the PyRanges object to file with `to_gtf`, but I got an error when trying to read it in again with `pr.read_gtf()` in a subsequent script.

Here's a reproducible example:
```
import pyranges as pr
import pandas as pd

gtf = pr.data.gencode_gtf()
gtf = gtf[gtf.transcript_id == "ENST00000456328.2"]
len(gtf)
# 4

gtf.dummy_attr = pd.Series(["abc"] + [""]*3)
gtf[["dummy_attr"]]
# +--------------+-----------+-----------+--------------+--------------+
# | Chromosome   |     Start |       End | Strand       | dummy_attr   |
# | (category)   |   (int32) |   (int32) | (category)   | (object)     |
# |--------------+-----------+-----------+--------------+--------------|
# | chr1         |     11868 |     14409 | +            | abc          |
# | chr1         |     11868 |     12227 | +            |              |
# | chr1         |     12612 |     12721 | +            |              |
# | chr1         |     13220 |     14409 | +            |              |
# +--------------+-----------+-----------+--------------+--------------+
# Stranded PyRanges object has 4 rows and 5 columns from 1 chromosomes.
# For printing, the PyRanges was sorted on Chromosome and Strand.

gtf.to_gtf("dummy_attr_test.gtf")
pr.read_gtf("dummy_attr_test.gtf")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sam/miniconda3/envs/pyranges/lib/python3.7/site-packages/pyranges/readers.py", line 311, in read_gtf
    gr = read_gtf_full(f, as_df, nrows, _skiprows, duplicate_attr)
  File "/home/sam/miniconda3/envs/pyranges/lib/python3.7/site-packages/pyranges/readers.py", line 343, in read_gtf_full
    extra = _to_rows(df.Attribute)
  File "/home/sam/miniconda3/envs/pyranges/lib/python3.7/site-packages/pyranges/readers.py", line 370, in to_rows
    for kv in l[:-1].split("; ")]})
  File "/home/sam/miniconda3/envs/pyranges/lib/python3.7/site-packages/pyranges/readers.py", line 368, in <dictcomp>
    for k, v in [kv.replace('"', '').split(None, 1)
ValueError: not enough values to unpack (expected 2, got 1)
```

Seems clear to me why this happens after trying the [code](https://github.com/biocore-ntnu/pyranges/blob/a36a2c7fac88f297bf41c529734c2cb6950bed3b/pyranges/readers.py#L357) in `to_rows` with an example_string:
```
x = """gene_id "abc1"; dummy_attr "";"""
for kv in x[:-1].split("; "):
     print(kv)
     print(kv.replace('"', '').split(None, 1))

# gene_id "abc1"
# ['gene_id', 'abc1']
# dummy_attr ""
# ['dummy_attr']
```

Of course on my end this is a simple fix (replace empty strings with e.g. 'not_found'), and it was probably not a smart idea to have empty strings in a GTF file to begin with (are empty values in an GTF attribute key-value pair even allowed in the specs?). I thought I should report regardless in case you consider it something worth changing or documenting (if someone else tries the same thing as me!).

Thanks :)

```
pr.version_info()
{'pyranges version': '0.0.115', 'pandas version': '1.1.0', 'numpy version': '1.19.1', 'python version': sys.version_info(major=3, minor=7, micro=11, releaselevel='final', serial=0), 'ncls': '0.0.63', 'sorted_nearest': '0.0.33', 'pyrle': '0.0.31', 'ray': '0.8.6', 'bamread': 'not installed', 'pyranges_db': 'not installed', 'pybigwig': 'not installed', 'hypothesis': 'not installed'}
```

**Comment by endrebak** [comment]
Perhaps I should wrap the whole thing in a try catch and match on different error cases with a more helpful message.

There are many weird edge-cases in gtf/gff formats.

I appreciate you reporting it :)

**Comment by yzJiang9** [comment]
Do you have any solution right now? Thanks!

**Comment by endrebak** [comment]
See #268 :)
