### ISSUE TITLE
Wrong number of dimensions error

### ISSUE THREAD

**Issue by jnasser3** [biocore-ntnu/pyranges#26]
I'm trying to work through some of the examples in the documentation and run into an error when trying to create pyranges objects:

>>> gr = pr.PyRanges(chromosomes="chr1", strands="+", starts=[0, 1, 2], ends=(3, 4, 5))
>>> print(gr)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jnasser/anaconda/lib/python3.6/site-packages/pyranges/pyranges.py", line 107, in __str__
    return tostring(self)
  File "/Users/jnasser/anaconda/lib/python3.6/site-packages/pyranges/tostring2.py", line 276, in tostring
    df = _get_df(self, n, sort)
  File "/Users/jnasser/anaconda/lib/python3.6/site-packages/pyranges/tostring2.py", line 72, in _get_df
    df = self.df.astype(object)
  File "/Users/jnasser/anaconda/lib/python3.6/site-packages/pandas/util/_decorators.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/Users/jnasser/anaconda/lib/python3.6/site-packages/pandas/core/generic.py", line 3299, in astype
    **kwargs)
  File "/Users/jnasser/anaconda/lib/python3.6/site-packages/pandas/core/internals.py", line 3224, in astype
    return self.apply('astype', dtype=dtype, **kwargs)
  File "/Users/jnasser/anaconda/lib/python3.6/site-packages/pandas/core/internals.py", line 3091, in apply
    applied = getattr(b, f)(**kwargs)
  File "/Users/jnasser/anaconda/lib/python3.6/site-packages/pandas/core/internals.py", line 471, in astype
    **kwargs)
  File "/Users/jnasser/anaconda/lib/python3.6/site-packages/pandas/core/internals.py", line 2197, in _astype
    return self.make_block(values)
  File "/Users/jnasser/anaconda/lib/python3.6/site-packages/pandas/core/internals.py", line 206, in make_block
    return make_block(values, placement=placement, ndim=ndim, **kwargs)
  File "/Users/jnasser/anaconda/lib/python3.6/site-packages/pandas/core/internals.py", line 2719, in make_block
    return klass(values, ndim=ndim, fastpath=fastpath, placement=placement)
  File "/Users/jnasser/anaconda/lib/python3.6/site-packages/pandas/core/internals.py", line 1844, in __init__
    placement=placement, **kwargs)
  File "/Users/jnasser/anaconda/lib/python3.6/site-packages/pandas/core/internals.py", line 106, in __init__
    raise ValueError('Wrong number of dimensions')
ValueError: Wrong number of dimensions

I get the same error when creating the pyranges object in other ways

pyranges version: 0.0.54

**Comment by endrebak** [comment]
I am looking into it now :) Thanks for reporting.

**Comment by endrebak** [comment]
Could not reproduce. Do these fail?:

```
#1 
pr.PyRanges(chromosomes=["chr1"] * 3, strands=["+"] * 3, starts=[0, 1, 2], ends=(3, 4, 5))

#2
df = pd.DataFrame({"Chromosome": "chr1", "Start": [0, 1, 2], "End": [3, 4, 5], "Strand": "+"})
pr.PyRanges(df)
```

?

My guess is that your pandas version is old. What is the output of `import pandas as pd; pd.__version__` ?

I'd love to be able to debug this so thanks for your help :)

**Comment by endrebak** [comment]
Could you also post the following:

`gr.df`, `gr.df.dtypes` after you have created the dataframe?

**Comment by jnasser3** [comment]
I am using pandas 0.20.1, so yes its a bit old.

Here is the output:

>>> gr = pr.PyRanges(chromosomes="chr1", strands="+", starts=[0, 1, 2], ends=(3, 4, 5))
>>> gr.df
  Chromosome  Start  End Strand
0       chr1      0    3      +
1       chr1      1    4      +
2       chr1      2    5      +
>>> gr.df.dtypes
Chromosome    category
Start            int32
End              int32
Strand        category
dtype: object

Options 1 and 2 above both failed as well.

**Comment by jnasser3** [comment]
I upgraded to pandas 0.25.1 and it works now

**Comment by endrebak** [comment]
Thanks for the feedback. I should add version requirements to pyranges so not closing this issue yet :)
