### ISSUE TITLE
`pr.read_gtf` returns error if the gtf records end with a semicolon

### ISSUE THREAD

**Issue by DongzeHE** [biocore-ntnu/pyranges#272]
Hello,

Thanks so much for providing such an excellent tool! 

I got a GTF file that is concatenated from two separated GTF files, one has a semicolon at the end of each line, one doesn't. `pyranges.read_gtf` was able to correctly parse the two separated GTF files, but not the concatenated one. Below were the error messages:

```
Traceback (most recent call last):
  File "/home/zaza/miniconda3/envs/pyroe/bin/pyroe", line 208, in <module>
    no_flanking_merge=args.no_flanking_merge,
  File "/home/zaza/miniconda3/envs/pyroe/lib/python3.7/site-packages/pyroe/make_splici_txome.py", line 255, in make_splici_txome
    gr = pr.read_gtf(gtf_path)
  File "/home/zaza/miniconda3/envs/pyroe/lib/python3.7/site-packages/pyranges/readers.py", line 311, in read_gtf
    gr = read_gtf_full(f, as_df, nrows, _skiprows, duplicate_attr)
  File "/home/zaza/miniconda3/envs/pyroe/lib/python3.7/site-packages/pyranges/readers.py", line 343, in read_gtf_full
    extra = _to_rows(df.Attribute)
  File "/home/zaza/miniconda3/envs/pyroe/lib/python3.7/site-packages/pyranges/readers.py", line 370, in to_rows
    for kv in l[:-1].split("; ")]})
TypeError: 'float' object is not subscriptable
``` 

Here are some lines from the concatenated GTF file:
```
...

ERCC-00067      ERCC    exon    1       644     0.000000        +       .       gene_id "ERCC-00067"; transcript_id "DQ883653";
ERCC-00069      ERCC    exon    1       1137    0.000000        +       .       gene_id "ERCC-00069"; transcript_id "DQ459421";
ERCC-00071      ERCC    exon    1       642     0.000000        +       .       gene_id "ERCC-00071"; transcript_id "DQ883654";
ERCC-00073      ERCC    exon    1       603     0.000000        +       .       gene_id "ERCC-00073"; transcript_id "DQ668358";
ERCC-00074      ERCC    exon    1       522     0.000000        +       .       gene_id "ERCC-00074"; transcript_id "DQ516754";
chr5	rtracklayer	exon	180803406	180803481	.	-	.exon_id "ENSE00002057340"; exon_rank 1; transcript_id "ENST00000512695"; gene_id "ENSG00000131446"; ID "ENST00000512695"
chr5	rtracklayer	exon	180803602	180803904	.	-	.exon_id "ENSE00001679536"; exon_rank 1; transcript_id "ENST00000427865"; gene_id "ENSG00000131446"; ID "ENST00000427865"
chr5	rtracklayer	exon	180803813	180803923	.	-	.exon_id "ENSE00002060237"; exon_rank 1; transcript_id "ENST00000514283"; gene_id "ENSG00000131446"; ID "ENST00000514283"
chr5	rtracklayer	exon	180808502	180808597	.	-	.exon_id "ENSE00002071796"; exon_rank 3; transcript_id "ENST00000504385"; gene_id "ENSG00000131446"; ID "ENST00000504385"
...

```

Hope this can help you to improve the robustness of the `read_gtf` function! Thank you so much.

Dongze

**Comment by endrebak** [comment]
Thanks. It seems like there always are problems with GTF due to its
underspecification and variations found in in the wild.
